### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by dimakiss** [V8gaming/Picture-To-Ascii#2]
Hey,
Here a few suggestions:
1. Get all the needed data from the console `python Picture-To-Ascii.py [path] [scale]`.
2. Add some explanation for how to use the code.
3. You can add a feature that saves an image from the text, it's very hard to past this mass of text somewhere else./

Hope to add some more and make a pull request later :)

**Comment by V8gaming** [comment]
I'll work on getting data from the console next. I'll try and add; -h for help, -i for interactive, -s for scale & -f for a specific frame. I have tried to do your third suggestion before and failed pretty badly. But yeah I'll work on your fist suggestion next.
